// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 8.7
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
jQuery("#wowslider-container3").wowSlider({effect:"basic",prev:"",next:"",duration:20*100,delay:20*100,width:896,height:550,autoPlay:true,autoPlayVideo:false,playPause:false,stopOnHover:true,loop:false,bullets:0,caption:false,captionEffect:"parallax",controls:true,controlsThumb:false,responsive:2,fullScreen:false,gestures:2,onBeforeStep:0,images:[{src:"./10.jpg",title:"1-0"},{src:"./11.jpg",title:"1-1"},{src:"./12.jpg",title:"1-2"},{src:"./14.jpg",title:"1-4"},{src:"./15.jpg",title:"1-5"},{src:"./16.jpg",title:"1-6"},{src:"./17.jpg",title:"1-7"},{src:"./18.jpg",title:"1-8"},{src:"./19.jpg",title:"1-9"},{src:"./110.jpg",title:"1-10",href:"http://wowslider.com"},{src:"./111.jpg",title:"1-11"}]});